CREATE TABLE "POINT"."MEMBER"  (	
	"ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"BIRTHDAY" DATE, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE_NUM" VARCHAR2(50 BYTE), 
	"ADDR" VARCHAR2(1000 BYTE), 
	"REG_DATE" DATE DEFAULT sysdate, 
	"ADDR_DETAIL" VARCHAR2(1000 BYTE), 
	"ADDR_NUM" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_MEMBER" PRIMARY KEY ("ID")
  );
  
   COMMENT ON COLUMN "POINT"."MEMBER"."ID" IS '아이디';
   COMMENT ON COLUMN "POINT"."MEMBER"."PASSWORD" IS '비밀번호';
   COMMENT ON COLUMN "POINT"."MEMBER"."NAME" IS '이름';
   COMMENT ON COLUMN "POINT"."MEMBER"."GENDER" IS '성별';
   COMMENT ON COLUMN "POINT"."MEMBER"."BIRTHDAY" IS '생일';
   COMMENT ON COLUMN "POINT"."MEMBER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "POINT"."MEMBER"."PHONE_NUM" IS '전화번호';
   COMMENT ON COLUMN "POINT"."MEMBER"."ADDR" IS '주소';
   COMMENT ON COLUMN "POINT"."MEMBER"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "POINT"."MEMBER"."ADDR_DETAIL" IS '상세주소';
   COMMENT ON COLUMN "POINT"."MEMBER"."ADDR_NUM" IS '우편번호';
   COMMENT ON TABLE "POINT"."MEMBER"  IS '회원가입';



CREATE TABLE POINT (
id VARCHAR2(20) PRIMARY KEY,
total_POINT NUMBER default 0 not null,
save NUMBER default 0 not null,
use NUMBER default 0 not null,
CONSTRAINT FK_POINT_id FOREIGN KEY(id)
REFERENCES member(id) on delete cascade
);

CREATE TABLE POINT_history ( 
id VARCHAR2(20),
POINT NUMBER default 0 not null,
flag NUMBER(2) not null,
p_date Date default sysdate 
);


CREATE TABLE "POINT"."BOARD" 
   (	"WRITE_NUM" NUMBER NOT NULL ENABLE, 
	"AUTHOR" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"SUBJECT" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"RE_GROUP" NUMBER NOT NULL ENABLE, 
	"RE_LEVEL" NUMBER NOT NULL ENABLE, 
	"RE_SEQ" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"READ_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "BOARD_PK" PRIMARY KEY ("WRITE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "POINT"."BOARD"."WRITE_NUM" IS '게시글번호';
   COMMENT ON COLUMN "POINT"."BOARD"."AUTHOR" IS '작성자ID';
   COMMENT ON COLUMN "POINT"."BOARD"."SUBJECT" IS '글제목';
   COMMENT ON COLUMN "POINT"."BOARD"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "POINT"."BOARD"."FILE_NAME" IS '첨부파일명';
   COMMENT ON COLUMN "POINT"."BOARD"."RE_GROUP" IS '글 그룹번호';
   COMMENT ON COLUMN "POINT"."BOARD"."RE_LEVEL" IS '답변글 깊이';
   COMMENT ON COLUMN "POINT"."BOARD"."RE_SEQ" IS '답변글 순서';
   COMMENT ON COLUMN "POINT"."BOARD"."READ_COUNT" IS '조회수';
   COMMENT ON COLUMN "POINT"."BOARD"."REG_DATE" IS '게시글 작성일자';



CREATE SEQUENCE  "POINT"."WRITE_NUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 321 CACHE 20 NOORDER  NOCYCLE ;